version: '2.1'

services:
  postgres:
    image: postgres:latest
    environment:
       POSTGRES_USER: admin
       POSTGRES_PASSWORD: adminer
       POSTGRES_DB: talent
    volumes:
       - /data/postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped
    
  adminer:
    image: adminer
    restart: always
    depends_on: 
      - postgres
    ports:
      - 8080:8080

networks:
  postgres:
    driver: bridge